FROM nginx:1.17-alpine
COPY organizations.json /usr/share/nginx/html/
COPY sortCriteria.json /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
